default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  host: db
  username: postgres
  password: postgres

development:
  <<: *default
  database: svg2pdf_convert_development

test:
  <<: *default
  database: svg2pdf_convert_test

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>
  prepared_statements: false
  advisory_locks: false

# cable:
#   <<: *production
